# Generated by Django 3.1.4 on 2020-12-18 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='pub_date',
            field=models.DateField(default=datetime.date(2020, 12, 18), verbose_name='date_published'),
        ),
    ]
