# Generated by Django 3.1.4 on 2021-01-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_memory_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='pub_date',
        ),
    ]
